import { describe, expect, test } from "bun:test";
import { renderToStaticMarkup } from "react-dom/server";
import { GetDown, type GetDownBoldProps, type GetDownCodeBlockProps, type GetDownInlineCodeProps, type GetDownLinkProps, type GetDownTableCellProps, type GetDownTableProps } from "./index";

interface GfmRenderingCase {
  section: string;
  name: string;
  markdown: string;
  html: string;
}

function render(markdown: string): string {
  return normalizeStaticMarkup(renderToStaticMarkup(<GetDown content={markdown} />));
}

function renderWithProps(props: Parameters<typeof GetDown>[0]): string {
  return normalizeStaticMarkup(renderToStaticMarkup(<GetDown {...props} />));
}

function normalizeStaticMarkup(html: string): string {
  return html
    .replace(/<link rel="preload" as="image" href="[^"]*"\/>/g, "")
    .replace(/<(br|hr)([^>]*?)\s*\/>/g, "<$1$2 />")
    .replace(/<input([^>]*?)\s*\/>/g, "<input$1 />")
    .replace(/<img([^>]*?)\s*\/>/g, "<img$1 />");
}

describe("GetDown resilience", () => {
  test("renders deeply nested blockquotes without overflowing the React stack", () => {
    expect(render(`${">".repeat(2_000)} deeply nested`)).toContain(
      "deeply nested",
    );
  });
});

export const gfmRenderingCases: GfmRenderingCase[] = [
  {
    section: "paragraphs",
    name: "single paragraph",
    markdown: "Hello, world!",
    html: "<p>Hello, world!</p>",
  },
  {
    section: "paragraphs",
    name: "two paragraphs",
    markdown: "Alpha\n\nBeta",
    html: "<p>Alpha</p><p>Beta</p>",
  },
  {
    section: "paragraphs",
    name: "soft line break",
    markdown: "Alpha\nBeta",
    html: "<p>Alpha\nBeta</p>",
  },
  {
    section: "paragraphs",
    name: "hard break with backslash",
    markdown: "Alpha\\\nBeta",
    html: "<p>Alpha<br />\nBeta</p>",
  },
  {
    section: "paragraphs",
    name: "hard break with two spaces",
    markdown: "Alpha  \nBeta",
    html: "<p>Alpha<br />\nBeta</p>",
  },
  {
    section: "paragraphs",
    name: "leading and trailing blank lines",
    markdown: "\n\nAlpha\n\n",
    html: "<p>Alpha</p>",
  },
  {
    section: "paragraphs",
    name: "paragraph with leading spaces up to three",
    markdown: "   Hello, world!",
    html: "<p>Hello, world!</p>",
  },
  {
    section: "paragraphs",
    name: "multiple consecutive hard breaks",
    markdown: "Alpha  \nBeta  \nGamma",
    html: "<p>Alpha<br />\nBeta<br />\nGamma</p>",
  },
  {
    section: "paragraphs",
    name: "hard break before blank line",
    markdown: "Alpha  \n\nBeta",
    html: "<p>Alpha<br />\n</p><p>Beta</p>",
  },
  {
    section: "paragraphs",
    name: "paragraph with only whitespace is collapsed",
    markdown: "   \n   ",
    html: "",
  },
  {
    section: "paragraphs",
    name: "paragraph with leading tabs",
    markdown: "\tHello, world!",
    html: "<pre><code>Hello, world!\n</code></pre>",
  },
  {
    section: "escaping",
    name: "html special characters are escaped in text",
    markdown: "1 < 2 && 3 > 2",
    html: "<p>1 &lt; 2 &amp;&amp; 3 &gt; 2</p>",
  },
  {
    section: "escaping",
    name: "backslash escapes punctuation",
    markdown: "\\*not emphasis\\* and \\# not a heading",
    html: "<p>*not emphasis* and # not a heading</p>",
  },
  {
    section: "escaping",
    name: "backslash before non escapable character remains",
    markdown: "\\a",
    html: "<p>\\a</p>",
  },
  {
    section: "escaping",
    name: "entity references",
    markdown: "&copy; &amp; &#35; &#x1F600;",
    html: "<p>© &amp; # 😀</p>",
  },
  {
    section: "escaping",
    name: "escaped backslash is single backslash",
    markdown: "\\\\",
    html: "<p>\\</p>",
  },
  {
    section: "escaping",
    name: "escaped exclamation prevents image",
    markdown: "\\!not image",
    html: "<p>!not image</p>",
  },
  {
    section: "escaping",
    name: "decimal numeric character reference",
    markdown: "&#128512;",
    html: "<p>😀</p>",
  },
  {
    section: "escaping",
    name: "hex numeric character reference lowercase",
    markdown: "&#x1f600;",
    html: "<p>😀</p>",
  },
  {
    section: "escaping",
    name: "entity references in sequence",
    markdown: "&lt;&amp;&gt;",
    html: "<p>&lt;&amp;&gt;</p>",
  },
  {
    section: "headings",
    name: "atx heading level one",
    markdown: "# Heading",
    html: "<h1>Heading</h1>",
  },
  {
    section: "headings",
    name: "atx heading level six",
    markdown: "###### Heading",
    html: "<h6>Heading</h6>",
  },
  {
    section: "headings",
    name: "closing hashes are stripped",
    markdown: "### Heading ###",
    html: "<h3>Heading</h3>",
  },
  {
    section: "headings",
    name: "more than six hashes is paragraph",
    markdown: "####### Heading",
    html: "<p>####### Heading</p>",
  },
  {
    section: "headings",
    name: "escaped heading marker is paragraph",
    markdown: "\\# Heading",
    html: "<p># Heading</p>",
  },
  {
    section: "headings",
    name: "setext heading level one",
    markdown: "Heading\n=======",
    html: "<h1>Heading</h1>",
  },
  {
    section: "headings",
    name: "setext heading level two",
    markdown: "Heading\n-------",
    html: "<h2>Heading</h2>",
  },
  {
    section: "headings",
    name: "heading contains inline emphasis",
    markdown: "## Hello *world* and **friends**",
    html: "<h2>Hello <em>world</em> and <strong>friends</strong></h2>",
  },
  {
    section: "headings",
    name: "atx heading without space is not a heading",
    markdown: "#Heading",
    html: "<p>#Heading</p>",
  },
  {
    section: "headings",
    name: "atx heading with leading spaces",
    markdown: "   # Heading",
    html: "<h1>Heading</h1>",
  },
  {
    section: "headings",
    name: "empty atx heading content",
    markdown: "#",
    html: "<h1></h1>",
  },
  {
    section: "headings",
    name: "atx heading level three after level one",
    markdown: "# Alpha\n\n### Beta",
    html: "<h1>Alpha</h1><h3>Beta</h3>",
  },
  {
    section: "headings",
    name: "setext heading preceded by blank line",
    markdown: "\nAlpha\n=====",
    html: "<h1>Alpha</h1>",
  },
  {
    section: "headings",
    name: "setext heading with leading spaces in text line",
    markdown: "   Alpha\n=====",
    html: "<h1>Alpha</h1>",
  },
  {
    section: "headings",
    name: "setext heading not formed when text has multiple lines before delimiter",
    markdown: "Alpha\nBeta\n=====",
    html: "<p>Alpha\nBeta\n=====</p>",
  },
  {
    section: "thematic breaks",
    name: "asterisk thematic break",
    markdown: "***",
    html: "<hr />",
  },
  {
    section: "thematic breaks",
    name: "dash thematic break with spaces",
    markdown: "- - -",
    html: "<hr />",
  },
  {
    section: "thematic breaks",
    name: "underscore thematic break",
    markdown: "___",
    html: "<hr />",
  },
  {
    section: "thematic breaks",
    name: "thematic break with interleaved spaces",
    markdown: "* * *",
    html: "<hr />",
  },
  {
    section: "thematic breaks",
    name: "thematic break with more than three characters",
    markdown: "*****",
    html: "<hr />",
  },
  {
    section: "thematic breaks",
    name: "two characters is not a thematic break",
    markdown: "--",
    html: "<p>--</p>",
  },
  {
    section: "thematic breaks",
    name: "mixed non-homogeneous characters is not a thematic break",
    markdown: "*-*",
    html: "<p>*-*</p>",
  },
  {
    section: "thematic breaks",
    name: "thematic break at start of document",
    markdown: "***\n\nAlpha",
    html: "<hr /><p>Alpha</p>",
  },
  {
    section: "thematic breaks",
    name: "thematic break without preceding blank line terminates paragraph",
    markdown: "Alpha\n***",
    html: "<p>Alpha</p><hr />",
  },
  {
    section: "emphasis",
    name: "asterisk emphasis",
    markdown: "This is *important*.",
    html: "<p>This is <em>important</em>.</p>",
  },
  {
    section: "emphasis",
    name: "underscore emphasis",
    markdown: "This is _important_.",
    html: "<p>This is <em>important</em>.</p>",
  },
  {
    section: "emphasis",
    name: "strong emphasis with asterisks",
    markdown: "This is **important**.",
    html: "<p>This is <strong>important</strong>.</p>",
  },
  {
    section: "emphasis",
    name: "repairs single leading asterisk with double trailing asterisks as strong",
    markdown: "*Navigating handoff procedure**",
    html: "<p><strong>Navigating handoff procedure</strong></p>",
  },
  {
    section: "emphasis",
    name: "strong emphasis with underscores",
    markdown: "This is __important__.",
    html: "<p>This is <strong>important</strong>.</p>",
  },
  {
    section: "emphasis",
    name: "nested emphasis inside strong",
    markdown: "**strong and *emphasized***",
    html: "<p><strong>strong and <em>emphasized</em></strong></p>",
  },
  {
    section: "emphasis",
    name: "strong inside emphasis",
    markdown: "*emphasized and **strong***",
    html: "<p><em>emphasized and <strong>strong</strong></em></p>",
  },
  {
    section: "emphasis",
    name: "intraword underscore does not emphasize",
    markdown: "foo_bar_baz",
    html: "<p>foo_bar_baz</p>",
  },
  {
    section: "emphasis",
    name: "intraword asterisk can emphasize",
    markdown: "foo*bar*baz",
    html: "<p>foo<em>bar</em>baz</p>",
  },
  {
    section: "emphasis",
    name: "triple asterisk is strong plus emphasis",
    markdown: "***both***",
    html: "<p><strong><em>both</em></strong></p>",
  },
  {
    section: "emphasis",
    name: "triple underscore is strong plus emphasis",
    markdown: "___both___",
    html: "<p><strong><em>both</em></strong></p>",
  },
  {
    section: "emphasis",
    name: "emphasis cannot cross paragraph boundary",
    markdown: "*alpha\n\nbeta*",
    html: "<p>*alpha</p><p>beta*</p>",
  },
  {
    section: "emphasis",
    name: "emphasis does not open when separated by spaces from content",
    markdown: "alpha * beta * gamma",
    html: "<p>alpha * beta * gamma</p>",
  },
  {
    section: "emphasis",
    name: "underscore in middle of word stays literal",
    markdown: "foo_bar_baz",
    html: "<p>foo_bar_baz</p>",
  },
  {
    section: "emphasis",
    name: "multiple emphases in one paragraph",
    markdown: "*alpha* and *beta* and *gamma*",
    html: "<p><em>alpha</em> and <em>beta</em> and <em>gamma</em></p>",
  },
  {
    section: "emphasis",
    name: "asterisk opens emphasis even before punctuation",
    markdown: "*(alpha*",
    html: "<p><em>(alpha</em></p>",
  },
  {
    section: "strikethrough",
    name: "simple strikethrough",
    markdown: "This is ~~deleted~~ text.",
    html: "<p>This is <del>deleted</del> text.</p>",
  },
  {
    section: "strikethrough",
    name: "strikethrough can contain emphasis",
    markdown: "~~deleted *with emphasis*~~",
    html: "<p><del>deleted <em>with emphasis</em></del></p>",
  },
  {
    section: "strikethrough",
    name: "single tilde is literal",
    markdown: "~not deleted~",
    html: "<p>~not deleted~</p>",
  },
  {
    section: "strikethrough",
    name: "strikethrough with leading space does not open",
    markdown: "~~ not deleted~~",
    html: "<p>~~ not deleted~~</p>",
  },
  {
    section: "strikethrough",
    name: "strikethrough with only spaces is literal",
    markdown: "~~ ~~",
    html: "<p>~~ ~~</p>",
  },
  {
    section: "strikethrough",
    name: "multiple strikethroughs in one paragraph",
    markdown: "~~alpha~~ and ~~beta~~",
    html: "<p><del>alpha</del> and <del>beta</del></p>",
  },
  {
    section: "strikethrough",
    name: "strikethrough containing code span",
    markdown: "~~deleted `code` here~~",
    html: "<p><del>deleted <code>code</code> here</del></p>",
  },
  {
    section: "strikethrough",
    name: "strikethrough containing strong",
    markdown: "~~deleted **strong** text~~",
    html: "<p><del>deleted <strong>strong</strong> text</del></p>",
  },
  {
    section: "code spans",
    name: "simple code span",
    markdown: "Use `const x = 1` here.",
    html: "<p>Use <code>const x = 1</code> here.</p>",
  },
  {
    section: "code spans",
    name: "code span escapes html",
    markdown: "`<script>alert(1)</script>`",
    html: "<p><code>&lt;script&gt;alert(1)&lt;/script&gt;</code></p>",
  },
  {
    section: "code spans",
    name: "double backticks allow single backtick",
    markdown: "``Use `code` here``",
    html: "<p><code>Use `code` here</code></p>",
  },
  {
    section: "code spans",
    name: "code span normalizes internal newlines to spaces",
    markdown: "`alpha\nbeta`",
    html: "<p><code>alpha beta</code></p>",
  },
  {
    section: "code spans",
    name: "code span strips one leading and trailing space",
    markdown: "` foo `",
    html: "<p><code>foo</code></p>",
  },
  {
    section: "code spans",
    name: "code span with only spaces becomes empty",
    markdown: "` `",
    html: "<p><code></code></p>",
  },
  {
    section: "code spans",
    name: "empty backtick pair is literal backticks",
    markdown: "````",
    html: "<p>````</p>",
  },
  {
    section: "code spans",
    name: "unmatched backtick count is literal",
    markdown: "``foo`",
    html: "<p>``foo`</p>",
  },
  {
    section: "code spans",
    name: "code span inside emphasis",
    markdown: "*italic with `code` inside*",
    html: "<p><em>italic with <code>code</code> inside</em></p>",
  },
  {
    section: "code spans",
    name: "code span inside link text is literal",
    markdown: "[`code` link](https://example.com)",
    html: "<p><a href=\"https://example.com\"><code>code</code> link</a></p>",
  },
  {
    section: "code spans",
    name: "multiple newlines in code span collapse to spaces",
    markdown: "`alpha\n\nbeta`",
    html: "<p><code>alpha  beta</code></p>",
  },
  {
    section: "links",
    name: "inline link",
    markdown: "[GitHub](https://github.com)",
    html: "<p><a href=\"https://github.com\">GitHub</a></p>",
  },
  {
    section: "links",
    name: "inline link with title",
    markdown: "[GitHub](https://github.com \"GitHub home\")",
    html: "<p><a href=\"https://github.com\" title=\"GitHub home\">GitHub</a></p>",
  },
  {
    section: "links",
    name: "link text contains emphasis",
    markdown: "[*GitHub*](https://github.com)",
    html: "<p><a href=\"https://github.com\"><em>GitHub</em></a></p>",
  },
  {
    section: "links",
    name: "reference link full",
    markdown: "[GitHub][gh]\n\n[gh]: https://github.com \"GitHub home\"",
    html: "<p><a href=\"https://github.com\" title=\"GitHub home\">GitHub</a></p>",
  },
  {
    section: "links",
    name: "reference link collapsed",
    markdown: "[GitHub][]\n\n[GitHub]: https://github.com",
    html: "<p><a href=\"https://github.com\">GitHub</a></p>",
  },
  {
    section: "links",
    name: "reference link shortcut",
    markdown: "[GitHub]\n\n[GitHub]: https://github.com",
    html: "<p><a href=\"https://github.com\">GitHub</a></p>",
  },
  {
    section: "links",
    name: "missing reference remains literal",
    markdown: "[GitHub][missing]",
    html: "<p>[GitHub][missing]</p>",
  },
  {
    section: "links",
    name: "inline link with angle brackets around destination",
    markdown: "[link](<https://github.com>)",
    html: "<p><a href=\"https://github.com\">link</a></p>",
  },
  {
    section: "links",
    name: "inline link with empty destination",
    markdown: "[link]()",
    html: "<p><a href=\"\">link</a></p>",
  },
  {
    section: "links",
    name: "inline link with empty text",
    markdown: "[](https://github.com)",
    html: "<p><a href=\"https://github.com\"></a></p>",
  },
  {
    section: "links",
    name: "reference link with title in parentheses",
    markdown: "[id]: https://example.com (title)\n\n[id]",
    html: "<p><a href=\"https://example.com\" title=\"title\">id</a></p>",
  },
  {
    section: "links",
    name: "link containing code span",
    markdown: "[`code`](https://github.com)",
    html: "<p><a href=\"https://github.com\"><code>code</code></a></p>",
  },
  {
    section: "links",
    name: "nested link brackets are literal",
    markdown: "[outer [inner] brackets](https://github.com)",
    html: "<p><a href=\"https://github.com\">outer [inner] brackets</a></p>",
  },
  {
    section: "links",
    name: "link destination with percent encoding",
    markdown: "[link](https://example.com/a%20b)",
    html: "<p><a href=\"https://example.com/a%20b\">link</a></p>",
  },
  {
    section: "links",
    name: "duplicate reference definition uses first",
    markdown: "[id]: https://first.com\n[id]: https://second.com\n\n[id]",
    html: "<p><a href=\"https://first.com\">id</a></p>",
  },
  {
    section: "links",
    name: "directionless link definition",
    markdown: "[foo]\n\n[foo]: https://example.com",
    html: "<p><a href=\"https://example.com\">foo</a></p>",
  },
  {
    section: "images",
    name: "inline image",
    markdown: "![Alt text](https://example.com/image.png)",
    html: "<p><img src=\"https://example.com/image.png\" alt=\"Alt text\" /></p>",
  },
  {
    section: "images",
    name: "inline image with title",
    markdown: "![Alt text](https://example.com/image.png \"Image title\")",
    html: "<p><img src=\"https://example.com/image.png\" alt=\"Alt text\" title=\"Image title\" /></p>",
  },
  {
    section: "images",
    name: "image alt text is plain text",
    markdown: "![*Alt* `code`](https://example.com/image.png)",
    html: "<p><img src=\"https://example.com/image.png\" alt=\"Alt code\" /></p>",
  },
  {
    section: "images",
    name: "reference image",
    markdown: "![alt][img]\n\n[img]: https://example.com/image.png",
    html: "<p><img src=\"https://example.com/image.png\" alt=\"alt\" /></p>",
  },
  {
    section: "images",
    name: "shortcut reference image",
    markdown: "![alt]\n\n[alt]: https://example.com/image.png",
    html: "<p><img src=\"https://example.com/image.png\" alt=\"alt\" /></p>",
  },
  {
    section: "images",
    name: "image with empty alt text",
    markdown: "![](https://example.com/image.png)",
    html: "<p><img src=\"https://example.com/image.png\" alt=\"\" /></p>",
  },
  {
    section: "images",
    name: "image with empty src is rendered without src",
    markdown: "![alt]()",
    html: "<p><img alt=\"alt\" /></p>",
  },
  {
    section: "images",
    name: "image inside link",
    markdown: "[![alt](image.png)](https://example.com)",
    html: "<p><a href=\"https://example.com\"><img src=\"image.png\" alt=\"alt\" /></a></p>",
  },
  {
    section: "images",
    name: "image alt text contains characters that need escaping",
    markdown: "![alt & text](https://example.com/image.png)",
    html: "<p><img src=\"https://example.com/image.png\" alt=\"alt &amp; text\" /></p>",
  },
  {
    section: "autolinks",
    name: "angle bracket autolink",
    markdown: "<https://github.com>",
    html: "<p><a href=\"https://github.com\">https://github.com</a></p>",
  },
  {
    section: "autolinks",
    name: "email autolink",
    markdown: "<user@example.com>",
    html: "<p><a href=\"mailto:user@example.com\">user@example.com</a></p>",
  },
  {
    section: "autolinks",
    name: "gfm literal url autolink",
    markdown: "Visit https://github.com now.",
    html: "<p>Visit <a href=\"https://github.com\">https://github.com</a> now.</p>",
  },
  {
    section: "autolinks",
    name: "gfm literal www autolink",
    markdown: "Visit www.github.com now.",
    html: "<p>Visit <a href=\"http://www.github.com\">www.github.com</a> now.</p>",
  },
  {
    section: "autolinks",
    name: "gfm literal email autolink",
    markdown: "Email user@example.com please.",
    html: "<p>Email <a href=\"mailto:user@example.com\">user@example.com</a> please.</p>",
  },
  {
    section: "autolinks",
    name: "url autolink with path and query",
    markdown: "<https://github.com/user/repo?q=foo>",
    html: "<p><a href=\"https://github.com/user/repo?q=foo\">https://github.com/user/repo?q=foo</a></p>",
  },
  {
    section: "autolinks",
    name: "email autolink with plus sign",
    markdown: "<user+tag@example.com>",
    html: "<p><a href=\"mailto:user+tag@example.com\">user+tag@example.com</a></p>",
  },
  {
    section: "autolinks",
    name: "gfm www autolink with path",
    markdown: "Visit www.example.com/page now.",
    html: "<p>Visit <a href=\"http://www.example.com/page\">www.example.com/page</a> now.</p>",
  },
  {
    section: "autolinks",
    name: "url autolink followed by punctuation is not part of link",
    markdown: "Visit https://github.com. now.",
    html: "<p>Visit <a href=\"https://github.com\">https://github.com</a>. now.</p>",
  },
  {
    section: "autolinks",
    name: "email autolink followed by period",
    markdown: "Email user@example.com.",
    html: "<p>Email <a href=\"mailto:user@example.com\">user@example.com</a>.</p>",
  },
  {
    section: "lists",
    name: "unordered list with hyphens",
    markdown: "- one\n- two",
    html: "<ul><li>one</li><li>two</li></ul>",
  },
  {
    section: "lists",
    name: "unordered list with asterisks",
    markdown: "* one\n* two",
    html: "<ul><li>one</li><li>two</li></ul>",
  },
  {
    section: "lists",
    name: "unordered list interrupts paragraph after label",
    markdown: "list:\n- item\n- item\n- item",
    html: "<p>list:</p><ul><li>item</li><li>item</li><li>item</li></ul>",
  },
  {
    section: "lists",
    name: "ordered list preserves start number",
    markdown: "3. three\n4. four",
    html: "<ol start=\"3\"><li>three</li><li>four</li></ol>",
  },
  {
    section: "lists",
    name: "ordered list with right paren delimiter",
    markdown: "1) one\n2) two",
    html: "<ol><li>one</li><li>two</li></ol>",
  },
  {
    section: "lists",
    name: "nested unordered list",
    markdown: "- one\n  - nested\n  - nested two\n- two",
    html: "<ul><li>one<ul><li>nested</li><li>nested two</li></ul></li><li>two</li></ul>",
  },
  {
    section: "lists",
    name: "nested ordered list",
    markdown: "1. one\n   1. nested\n   2. nested two\n2. two",
    html: "<ol><li>one<ol><li>nested</li><li>nested two</li></ol></li><li>two</li></ol>",
  },
  {
    section: "lists",
    name: "loose unordered list",
    markdown: "- one\n\n- two",
    html: "<ul><li><p>one</p></li><li><p>two</p></li></ul>",
  },
  {
    section: "lists",
    name: "list item with paragraph continuation",
    markdown: "- one\n  continued\n- two",
    html: "<ul><li>one\ncontinued</li><li>two</li></ul>",
  },
  {
    section: "lists",
    name: "list item with block quote",
    markdown: "- item\n  > quote",
    html: "<ul><li>item<blockquote><p>quote</p></blockquote></li></ul>",
  },
  {
    section: "lists",
    name: "unordered list with plus sign",
    markdown: "+ one\n+ two",
    html: "<ul><li>one</li><li>two</li></ul>",
  },
  {
    section: "lists",
    name: "ordered list nested inside unordered",
    markdown: "- one\n  1. nested\n  2. nested two\n- two",
    html: "<ul><li>one<ol><li>nested</li><li>nested two</li></ol></li><li>two</li></ul>",
  },
  {
    section: "lists",
    name: "unordered list nested inside ordered",
    markdown: "1. one\n   - nested\n   - nested two\n2. two",
    html: "<ol><li>one<ul><li>nested</li><li>nested two</li></ul></li><li>two</li></ol>",
  },
  {
    section: "lists",
    name: "blank line in list item starts loose mode",
    markdown: "- one\n\n  continued\n- two",
    html: "<ul><li><p>one</p><p>continued</p></li><li><p>two</p></li></ul>",
  },
  {
    section: "lists",
    name: "list item with fenced code block",
    markdown: "- item\n\n  ```\n  code\n  ```",
    html: "<ul><li><p>item</p><pre><code>code\n</code></pre></li></ul>",
  },
  {
    section: "lists",
    name: "list with mixed unordered markers creates separate lists",
    markdown: "- one\n+ two",
    html: "<ul><li>one</li></ul><ul><li>two</li></ul>",
  },
  {
    section: "lists",
    name: "ordered list with right paren and start number",
    markdown: "3) three\n4) four",
    html: "<ol start=\"3\"><li>three</li><li>four</li></ol>",
  },
  {
    section: "lists",
    name: "ordered list maintains start number with nesting",
    markdown: "3. three\n   4. nested",
    html: "<ol start=\"3\"><li>three<ol start=\"4\"><li>nested</li></ol></li></ol>",
  },
  {
    section: "lists",
    name: "empty list item",
    markdown: "- one\n-\n- two",
    html: "<ul><li>one</li><li></li><li>two</li></ul>",
  },
  {
    section: "lists",
    name: "list item with heading",
    markdown: "- # Heading",
    html: "<ul><li><h1>Heading</h1></li></ul>",
  },
  {
    section: "task lists",
    name: "unchecked task list item",
    markdown: "- [ ] todo",
    html: "<ul><li><input type=\"checkbox\" disabled=\"\" /> todo</li></ul>",
  },
  {
    section: "task lists",
    name: "checked task list item lowercase x",
    markdown: "- [x] done",
    html: "<ul><li><input type=\"checkbox\" disabled=\"\" checked=\"\" /> done</li></ul>",
  },
  {
    section: "task lists",
    name: "checked task list item uppercase x",
    markdown: "- [X] done",
    html: "<ul><li><input type=\"checkbox\" disabled=\"\" checked=\"\" /> done</li></ul>",
  },
  {
    section: "task lists",
    name: "nested task list items",
    markdown: "- [x] parent\n  - [ ] child",
    html: "<ul><li><input type=\"checkbox\" disabled=\"\" checked=\"\" /> parent<ul><li><input type=\"checkbox\" disabled=\"\" /> child</li></ul></li></ul>",
  },
  {
    section: "task lists",
    name: "task list in ordered list",
    markdown: "1. [x] done\n2. [ ] todo",
    html: "<ol><li><input type=\"checkbox\" disabled=\"\" checked=\"\" /> done</li><li><input type=\"checkbox\" disabled=\"\" /> todo</li></ol>",
  },
  {
    section: "task lists",
    name: "task item without space after bracket is not a task",
    markdown: "- [x]valid",
    html: "<ul><li>[x]valid</li></ul>",
  },
  {
    section: "task lists",
    name: "invalid task format is not a task",
    markdown: "-[ ] not a task",
    html: "<p>-[ ] not a task</p>",
  },
  {
    section: "task lists",
    name: "task list item with paragraph continuation",
    markdown: "- [x] done\n  continued",
    html: "<ul><li><input type=\"checkbox\" disabled=\"\" checked=\"\" /> done\ncontinued</li></ul>",
  },
  {
    section: "block quotes",
    name: "simple block quote",
    markdown: "> quoted",
    html: "<blockquote><p>quoted</p></blockquote>",
  },
  {
    section: "block quotes",
    name: "lazy continuation",
    markdown: "> quoted\ncontinued",
    html: "<blockquote><p>quoted\ncontinued</p></blockquote>",
  },
  {
    section: "block quotes",
    name: "nested block quotes",
    markdown: "> outer\n> > inner",
    html: "<blockquote><p>outer</p><blockquote><p>inner</p></blockquote></blockquote>",
  },
  {
    section: "block quotes",
    name: "block quote with list",
    markdown: "> - one\n> - two",
    html: "<blockquote><ul><li>one</li><li>two</li></ul></blockquote>",
  },
  {
    section: "block quotes",
    name: "block quote with code block",
    markdown: "> ```\n> code\n> ```",
    html: "<blockquote><pre><code>code\n</code></pre></blockquote>",
  },
  {
    section: "block quotes",
    name: "block quote with heading",
    markdown: "> # Heading",
    html: "<blockquote><h1>Heading</h1></blockquote>",
  },
  {
    section: "block quotes",
    name: "block quote with thematic break",
    markdown: "> ***",
    html: "<blockquote><hr /></blockquote>",
  },
  {
    section: "block quotes",
    name: "empty block quote",
    markdown: ">",
    html: "<blockquote></blockquote>",
  },
  {
    section: "block quotes",
    name: "block quote with lazy continuation and blank line",
    markdown: "> quoted\n\ncontinued",
    html: "<blockquote><p>quoted</p></blockquote><p>continued</p>",
  },
  {
    section: "block quotes",
    name: "block quote containing paragraph and nested quote",
    markdown: "> alpha\n>\n> > nested",
    html: "<blockquote><p>alpha</p><blockquote><p>nested</p></blockquote></blockquote>",
  },
  {
    section: "code blocks",
    name: "indented code block",
    markdown: "    const x = 1;\n    console.log(x);",
    html: "<pre><code>const x = 1;\nconsole.log(x);\n</code></pre>",
  },
  {
    section: "code blocks",
    name: "fenced code block with backticks",
    markdown: "```\nconst x = 1;\n```",
    html: "<pre><code>const x = 1;\n</code></pre>",
  },
  {
    section: "code blocks",
    name: "fenced code block with tildes",
    markdown: "~~~\nconst x = 1;\n~~~",
    html: "<pre><code>const x = 1;\n</code></pre>",
  },
  {
    section: "code blocks",
    name: "fenced code block with info string",
    markdown: "```ts\nconst x: number = 1;\n```",
    html: "<pre><code class=\"language-ts\">const x: number = 1;\n</code></pre>",
  },
  {
    section: "code blocks",
    name: "fenced code block escapes html",
    markdown: "```html\n<div>safe text</div>\n```",
    html: "<pre><code class=\"language-html\">&lt;div&gt;safe text&lt;/div&gt;\n</code></pre>",
  },
  {
    section: "code blocks",
    name: "unclosed fenced code block consumes to end",
    markdown: "```\nunterminated",
    html: "<pre><code>unterminated\n</code></pre>",
  },
  {
    section: "code blocks",
    name: "indented code block follows paragraph",
    markdown: "Alpha\n\n    code",
    html: "<p>Alpha</p><pre><code>code\n</code></pre>",
  },
  {
    section: "code blocks",
    name: "fenced code block within list item",
    markdown: "- item\n\n  ```\n  code\n  ```",
    html: "<ul><li><p>item</p><pre><code>code\n</code></pre></li></ul>",
  },
  {
    section: "code blocks",
    name: "fenced code block within block quote",
    markdown: "> ```\n> code\n> ```",
    html: "<blockquote><pre><code>code\n</code></pre></blockquote>",
  },
  {
    section: "code blocks",
    name: "fenced code block with longer closing fence",
    markdown: "```\ncode\n`````",
    html: "<pre><code>code\n</code></pre>",
  },
  {
    section: "code blocks",
    name: "empty fenced code block",
    markdown: "```\n```",
    html: "<pre><code></code></pre>",
  },
  {
    section: "code blocks",
    name: "fenced code block with blank line at start",
    markdown: "```\n\ncode\n```",
    html: "<pre><code>\ncode\n</code></pre>",
  },
  {
    section: "code blocks",
    name: "indented code block preserves indentation",
    markdown: "    line one\n      line two",
    html: "<pre><code>line one\n  line two\n</code></pre>",
  },
  {
    section: "code blocks",
    name: "fenced code block with trailing spaces in info string",
    markdown: "```ts  \ncode\n```",
    html: "<pre><code class=\"language-ts\">code\n</code></pre>",
  },
  {
    section: "html",
    name: "inline html is escaped",
    markdown: "Hello <span>world</span>.",
    html: "<p>Hello &lt;span&gt;world&lt;/span&gt;.</p>",
  },
  {
    section: "html",
    name: "html block is escaped as paragraph text",
    markdown: "<div>\n  <strong>Hello</strong>\n</div>",
    html: "<p>&lt;div&gt;\n&lt;strong&gt;Hello&lt;/strong&gt;\n&lt;/div&gt;</p>",
  },
  {
    section: "html",
    name: "markdown is parsed normally around escaped html text",
    markdown: "<div>\n**strong text**\n</div>",
    html: "<p>&lt;div&gt;\n<strong>strong text</strong>\n&lt;/div&gt;</p>",
  },
  {
    section: "html",
    name: "html comment is escaped",
    markdown: "<!-- comment -->\n\nalpha",
    html: "<p>&lt;!-- comment --&gt;</p><p>alpha</p>",
  },
  {
    section: "html",
    name: "self-closing html inline is escaped",
    markdown: "alpha<br />beta",
    html: "<p>alpha&lt;br /&gt;beta</p>",
  },
  {
    section: "html",
    name: "inline html with attributes is escaped",
    markdown: "alpha <span class=\"highlight\">beta</span> gamma",
    html: "<p>alpha &lt;span class=&quot;highlight&quot;&gt;beta&lt;/span&gt; gamma</p>",
  },
  {
    section: "html",
    name: "html block text is escaped between paragraphs",
    markdown: "alpha\n\n<div>\n  beta\n</div>\n\ngamma",
    html: "<p>alpha</p><p>&lt;div&gt;\nbeta\n&lt;/div&gt;</p><p>gamma</p>",
  },
  {
    section: "html",
    name: "inline html inside emphasis is escaped",
    markdown: "*alpha <span>beta</span> gamma*",
    html: "<p><em>alpha &lt;span&gt;beta&lt;/span&gt; gamma</em></p>",
  },
  {
    section: "html",
    name: "raw void element is escaped as paragraph text",
    markdown: "<hr>",
    html: "<p>&lt;hr&gt;</p>",
  },
  {
    section: "tables",
    name: "simple table",
    markdown: "| A | B |\n| - | - |\n| 1 | 2 |",
    html: "<table><thead><tr><th>A</th><th>B</th></tr></thead><tbody><tr><td>1</td><td>2</td></tr></tbody></table>",
  },
  {
    section: "tables",
    name: "table alignments",
    markdown: "| Left | Center | Right |\n| :--- | :----: | ----: |\n| a | b | c |",
    html: "<table><thead><tr><th align=\"left\">Left</th><th align=\"center\">Center</th><th align=\"right\">Right</th></tr></thead><tbody><tr><td align=\"left\">a</td><td align=\"center\">b</td><td align=\"right\">c</td></tr></tbody></table>",
  },
  {
    section: "tables",
    name: "table without leading and trailing pipes",
    markdown: "A | B\n- | -\n1 | 2",
    html: "<table><thead><tr><th>A</th><th>B</th></tr></thead><tbody><tr><td>1</td><td>2</td></tr></tbody></table>",
  },
  {
    section: "tables",
    name: "table cell inline markdown",
    markdown: "| A | B |\n| - | - |\n| **strong** | `code` |",
    html: "<table><thead><tr><th>A</th><th>B</th></tr></thead><tbody><tr><td><strong>strong</strong></td><td><code>code</code></td></tr></tbody></table>",
  },
  {
    section: "tables",
    name: "escaped pipe in table cell",
    markdown: "| A | B |\n| - | - |\n| a \\| b | c |",
    html: "<table><thead><tr><th>A</th><th>B</th></tr></thead><tbody><tr><td>a | b</td><td>c</td></tr></tbody></table>",
  },
  {
    section: "tables",
    name: "extra table cells are ignored",
    markdown: "| A | B |\n| - | - |\n| 1 | 2 | 3 |",
    html: "<table><thead><tr><th>A</th><th>B</th></tr></thead><tbody><tr><td>1</td><td>2</td></tr></tbody></table>",
  },
  {
    section: "tables",
    name: "missing table cells are empty",
    markdown: "| A | B |\n| - | - |\n| 1 |",
    html: "<table><thead><tr><th>A</th><th>B</th></tr></thead><tbody><tr><td>1</td><td></td></tr></tbody></table>",
  },
  {
    section: "tables",
    name: "single column table",
    markdown: "| A |\n| - |\n| 1 |",
    html: "<table><thead><tr><th>A</th></tr></thead><tbody><tr><td>1</td></tr></tbody></table>",
  },
  {
    section: "tables",
    name: "table with empty cells",
    markdown: "| A | B |\n| - | - |\n| | |",
    html: "<table><thead><tr><th>A</th><th>B</th></tr></thead><tbody><tr><td></td><td></td></tr></tbody></table>",
  },
  {
    section: "tables",
    name: "table without body rows",
    markdown: "| A | B |\n| - | - |",
    html: "<table><thead><tr><th>A</th><th>B</th></tr></thead></table>",
  },
  {
    section: "tables",
    name: "table with multiple body rows",
    markdown: "| A | B |\n| - | - |\n| 1 | 2 |\n| 3 | 4 |",
    html: "<table><thead><tr><th>A</th><th>B</th></tr></thead><tbody><tr><td>1</td><td>2</td></tr><tr><td>3</td><td>4</td></tr></tbody></table>",
  },
  {
    section: "tables",
    name: "delimiter row with fewer columns than header",
    markdown: "| A | B | C |\n| - | - |\n| 1 | 2 | 3 |",
    html: "<table><thead><tr><th>A</th><th>B</th><th>C</th></tr></thead><tbody><tr><td>1</td><td>2</td><td>3</td></tr></tbody></table>",
  },
  {
    section: "tables",
    name: "table immediately followed by paragraph",
    markdown: "| A |\n| - |\n| 1 |\nalpha",
    html: "<table><thead><tr><th>A</th></tr></thead><tbody><tr><td>1</td></tr></tbody></table><p>alpha</p>",
  },
  {
    section: "tables",
    name: "table with center alignment only",
    markdown: "| A |\n| :---: |\n| 1 |",
    html: "<table><thead><tr><th align=\"center\">A</th></tr></thead><tbody><tr><td align=\"center\">1</td></tr></tbody></table>",
  },
  {
    section: "definitions",
    name: "link definition is not rendered",
    markdown: "[id]: https://example.com",
    html: "",
  },
  {
    section: "definitions",
    name: "link definition can be indented up to three spaces",
    markdown: "   [id]: https://example.com\n\n[id]",
    html: "<p><a href=\"https://example.com\">id</a></p>",
  },
  {
    section: "definitions",
    name: "four-space indented link definition is code",
    markdown: "    [id]: https://example.com",
    html: "<pre><code>[id]: https://example.com\n</code></pre>",
  },
  {
    section: "definitions",
    name: "link definition with title in parentheses",
    markdown: "[id]: https://example.com (title)\n\n[id]",
    html: "<p><a href=\"https://example.com\" title=\"title\">id</a></p>",
  },
  {
    section: "definitions",
    name: "link definition label is case-insensitive",
    markdown: "[ID]: https://example.com\n\n[id]",
    html: "<p><a href=\"https://example.com\">id</a></p>",
  },
  {
    section: "definitions",
    name: "link definition label folding trims whitespace",
    markdown: "[  id  ]: https://example.com\n\n[id]",
    html: "<p><a href=\"https://example.com\">id</a></p>",
  },
  {
    section: "complex documents",
    name: "mixed document with heading quote list and table",
    markdown: "# Title\n\n> Intro with **strong** text.\n\n- [x] done\n- [ ] todo\n\n| Name | Value |\n| --- | ---: |\n| A | 1 |\n| B | 2 |",
    html: "<h1>Title</h1><blockquote><p>Intro with <strong>strong</strong> text.</p></blockquote><ul><li><input type=\"checkbox\" disabled=\"\" checked=\"\" /> done</li><li><input type=\"checkbox\" disabled=\"\" /> todo</li></ul><table><thead><tr><th>Name</th><th align=\"right\">Value</th></tr></thead><tbody><tr><td>A</td><td align=\"right\">1</td></tr><tr><td>B</td><td align=\"right\">2</td></tr></tbody></table>",
  },
  {
    section: "complex documents",
    name: "inline precedence code beats emphasis and links",
    markdown: "`**not strong** [not a link](https://example.com)` and **strong**",
    html: "<p><code>**not strong** [not a link](https://example.com)</code> and <strong>strong</strong></p>",
  },
  {
    section: "complex documents",
    name: "link destination containing escaped parenthesis",
    markdown: "[link](https://example.com/foo\\)bar)",
    html: "<p><a href=\"https://example.com/foo)bar\">link</a></p>",
  },
  {
    section: "complex documents",
    name: "image inside link",
    markdown: "[![alt](image.png)](https://example.com)",
    html: "<p><a href=\"https://example.com\"><img src=\"image.png\" alt=\"alt\" /></a></p>",
  },
  {
    section: "complex documents",
    name: "unicode text and emoji",
    markdown: "Привет **мир** 😀",
    html: "<p>Привет <strong>мир</strong> 😀</p>",
  },
  {
    section: "complex documents",
    name: "carriage returns normalize to line feeds",
    markdown: "# Title\r\n\r\nText",
    html: "<h1>Title</h1><p>Text</p>",
  },
  {
    section: "complex documents",
    name: "null character replacement",
    markdown: "a\u0000b",
    html: "<p>a�b</p>",
  },
  {
    section: "complex documents",
    name: "empty string",
    markdown: "",
    html: "",
  },
  {
    section: "complex documents",
    name: "only whitespace and blank lines",
    markdown: "   \n\n   ",
    html: "",
  },
  {
    section: "complex documents",
    name: "only blank lines",
    markdown: "\n\n\n",
    html: "",
  },
  {
    section: "complex documents",
    name: "multiple consecutive thematic breaks",
    markdown: "***\n\n---\n\n___",
    html: "<hr /><hr /><hr />",
  },
  {
    section: "complex documents",
    name: "deeply nested block quote list and code",
    markdown: "> - item\n>   ```\n>   nested code\n>   ```",
    html: "<blockquote><ul><li>item<pre><code>nested code\n</code></pre></li></ul></blockquote>",
  },
  {
    section: "complex documents",
    name: "heading after heading without blank line",
    markdown: "# Alpha\n# Beta",
    html: "<h1>Alpha</h1><h1>Beta</h1>",
  },
  {
    section: "complex documents",
    name: "paragraph with inline image link emphasis and code",
    markdown: "See **our** ![logo](img.png) and `code` [here](https://ex.com).",
    html: "<p>See <strong>our</strong> <img src=\"img.png\" alt=\"logo\" /> and <code>code</code> <a href=\"https://ex.com\">here</a>.</p>",
  },
  {
    section: "complex documents",
    name: "list with task block quote and nested list",
    markdown: "- [x] task\n  > quote\n  - nested",
    html: "<ul><li><input type=\"checkbox\" disabled=\"\" checked=\"\" /> task<blockquote><p>quote</p></blockquote><ul><li>nested</li></ul></li></ul>",
  },
  {
    section: "complex documents",
    name: "code block preserves blank lines internally",
    markdown: "```\nalpha\n\nbeta\n\ngamma\n```",
    html: "<pre><code>alpha\n\nbeta\n\ngamma\n</code></pre>",
  },
  {
    section: "complex documents",
    name: "table with inline emphasis code and link in cells",
    markdown: "| **A** | `B` | [C](https://ex.com) |\n| --- | --- | --- |\n| **1** | `2` | [3](https://ex.com) |",
    html: "<table><thead><tr><th><strong>A</strong></th><th><code>B</code></th><th><a href=\"https://ex.com\">C</a></th></tr></thead><tbody><tr><td><strong>1</strong></td><td><code>2</code></td><td><a href=\"https://ex.com\">3</a></td></tr></tbody></table>",
  },
  {
    section: "complex documents",
    name: "setext heading followed by paragraph",
    markdown: "Title\n=====\n\nParagraph.",
    html: "<h1>Title</h1><p>Paragraph.</p>",
  },
  {
    section: "complex documents",
    name: "strikethrough spanning most of paragraph",
    markdown: "Keep ~~deleted and **strong** plus `code`~~ end.",
    html: "<p>Keep <del>deleted and <strong>strong</strong> plus <code>code</code></del> end.</p>",
  },
  {
    section: "complex documents",
    name: "reference links with images and multiple definitions",
    markdown: "[img][]\n\n![img][]\n\n[img]: https://example.com/pic.png",
    html: "<p><a href=\"https://example.com/pic.png\">img</a></p><p><img src=\"https://example.com/pic.png\" alt=\"img\" /></p>",
  },
  {
    section: "complex documents",
    name: "tight list with block quote at end",
    markdown: "- item\n  > quote\n- another",
    html: "<ul><li>item<blockquote><p>quote</p></blockquote></li><li>another</li></ul>",
  },
  {
    section: "complex documents",
    name: "hard break in list item",
    markdown: "- alpha  \n  beta",
    html: "<ul><li>alpha<br />\nbeta</li></ul>",
  },
  {
    section: "complex documents",
    name: "triple backtick fence with backtick content",
    markdown: "```\ncode `with` backticks\n```",
    html: "<pre><code>code `with` backticks\n</code></pre>",
  },
  {
    section: "complex documents",
    name: "thousands of characters in single paragraph",
    markdown: "A".repeat(1000),
    html: `<p>${"A".repeat(1000)}</p>`,
  },
  {
    section: "complex documents",
    name: "bullet list with flat items at varying indentation",
    markdown: "- one\n - two\n- three",
    html: "<ul><li>one</li><li>two</li><li>three</li></ul>",
  },
  {
    section: "complex documents",
    name: "ordered list with reversed numbers",
    markdown: "3. alpha\n2. beta\n1. gamma",
    html: "<ol start=\"3\"><li>alpha</li><li>beta</li><li>gamma</li></ol>",
  },
  {
    section: "complex documents",
    name: "code span with literal tilde characters",
    markdown: "`~~strikethrough~~`",
    html: "<p><code>~~strikethrough~~</code></p>",
  },
  {
    section: "complex documents",
    name: "link text contains backslash escapes",
    markdown: "[\\(link\\)](https://example.com)",
    html: "<p><a href=\"https://example.com\">(link)</a></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated asterisk emphasis auto-closes at end",
    markdown: "*val",
    html: "<p><em>val</em></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated underscore emphasis auto-closes at end",
    markdown: "_val",
    html: "<p><em>val</em></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated double asterisk strong auto-closes at end",
    markdown: "**val",
    html: "<p><strong>val</strong></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated double underscore strong auto-closes at end",
    markdown: "__val",
    html: "<p><strong>val</strong></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated triple asterisk strong-em auto-closes at end",
    markdown: "***val",
    html: "<p><strong><em>val</em></strong></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated triple underscore strong-em auto-closes at end",
    markdown: "___val",
    html: "<p><strong><em>val</em></strong></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated strikethrough auto-closes at end",
    markdown: "~~val",
    html: "<p><del>val</del></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated code span auto-closes at end",
    markdown: "`val",
    html: "<p><code>val</code></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated inline link auto-closes paren at end",
    markdown: "[text](url",
    html: "<p><a href=\"url\">text</a></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated inline link auto-closes bracket and paren",
    markdown: "[text",
    html: "<p>[text]</p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated link bracket before open paren auto-closes",
    markdown: "[text](",
    html: "<p><a href=\"\">text</a></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated inline image auto-closes paren at end",
    markdown: "![alt](url",
    html: "<p><img src=\"url\" alt=\"alt\" /></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated angle bracket autolink auto-closes at end",
    markdown: "<https://github.com",
    html: "<p><a href=\"https://github.com\">https://github.com</a></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated angle bracket email auto-closes at end",
    markdown: "<user@example.com",
    html: "<p><a href=\"mailto:user@example.com\">user@example.com</a></p>",
  },
  {
    section: "optimistic closing",
    name: "emphasis inside unterminated strong auto-closes both",
    markdown: "**strong and *em",
    html: "<p><strong>strong and <em>em</em></strong></p>",
  },
  {
    section: "optimistic closing",
    name: "strong inside unterminated emphasis auto-closes both",
    markdown: "*em and **strong",
    html: "<p><em>em and <strong>strong</strong></em></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated strikethrough containing emphasis auto-closes",
    markdown: "~~del *em",
    html: "<p><del>del <em>em</em></del></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated emphasis containing strikethrough auto-closes",
    markdown: "*em ~~del",
    html: "<p><em>em <del>del</del></em></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated link with emphasis in text auto-closes",
    markdown: "[*em](url",
    html: "<p><a href=\"url\"><em>em</em></a></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated emphasis surrounding link auto-closes",
    markdown: "*em [text](url",
    html: "<p><em>em <a href=\"url\">text</a></em></p>",
  },
  {
    section: "optimistic closing",
    name: "triple nested unterminated auto-closes all layers",
    markdown: "~~del **strong *em",
    html: "<p><del>del <strong>strong <em>em</em></strong></del></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated formatting before text then normal text follows",
    markdown: "*em rest of paragraph",
    html: "<p><em>em</em> rest of paragraph</p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated formatting mid-paragraph consumes to end",
    markdown: "before *em",
    html: "<p>before <em>em</em></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated formatting before properly closed formatting",
    markdown: "*open and **closed**",
    html: "<p><em>open and <strong>closed</strong></em></p>",
  },
  {
    section: "optimistic closing",
    name: "properly closed formatting before unterminated formatting",
    markdown: "**closed** and *open",
    html: "<p><strong>closed</strong> and <em>open</em></p>",
  },
  {
    section: "optimistic closing",
    name: "adjacent unterminated spans auto-close independently",
    markdown: "*alpha*beta",
    html: "<p><em>alpha</em>beta</p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated formatting at start of paragraph with line break",
    markdown: "*alpha\nbeta",
    html: "<p><em>alpha\nbeta</em></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated formatting in heading auto-closes",
    markdown: "# Heading *em",
    html: "<h1>Heading <em>em</em></h1>",
  },
  {
    section: "optimistic closing",
    name: "unterminated formatting in block quote auto-closes",
    markdown: "> quoted *em",
    html: "<blockquote><p>quoted <em>em</em></p></blockquote>",
  },
  {
    section: "optimistic closing",
    name: "unterminated formatting in list item auto-closes",
    markdown: "- item *em",
    html: "<ul><li>item <em>em</em></li></ul>",
  },
  {
    section: "optimistic closing",
    name: "unterminated formatting in tight list continuation auto-closes",
    markdown: "- item\n  continued *em",
    html: "<ul><li>item\ncontinued <em>em</em></li></ul>",
  },
  {
    section: "optimistic closing",
    name: "unterminated formatting in table cell auto-closes",
    markdown: "| A |\n| - |\n| *em |",
    html: "<table><thead><tr><th>A</th></tr></thead><tbody><tr><td><em>em</em></td></tr></tbody></table>",
  },
  {
    section: "optimistic closing",
    name: "unterminated double backtick code span auto-closes",
    markdown: "``val",
    html: "<p><code>val</code></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated link with title auto-closes paren and title quote",
    markdown: "[text](url \"title",
    html: "<p><a href=\"url\" title=\"title\">text</a></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated link with single-quote title auto-closes",
    markdown: "[text](url 'title",
    html: "<p><a href=\"url\" title=\"title\">text</a></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated link with parenthesized title auto-closes",
    markdown: "[text](url (title",
    html: "<p><a href=\"url\" title=\"title\">text</a></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated image with title auto-closes",
    markdown: "![alt](url \"title",
    html: "<p><img src=\"url\" alt=\"alt\" title=\"title\" /></p>",
  },
  {
    section: "optimistic closing",
    name: "only opening emphasis marker without content produces no output",
    markdown: "*",
    html: "<p>*</p>",
  },
  {
    section: "optimistic closing",
    name: "multiple unterminated same-type spans in paragraph",
    markdown: "*alpha *beta *gamma",
    html: "<p><em>alpha <em>beta <em>gamma</em></em></em></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated strong in link text auto-closes",
    markdown: "[**strong](url",
    html: "<p><a href=\"url\"><strong>strong</strong></a></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated code span in link text auto-closes",
    markdown: "[`code](url",
    html: "<p><a href=\"url\"><code>code</code></a></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated formatting in setext heading auto-closes",
    markdown: "Heading *em\n=====",
    html: "<h1>Heading <em>em</em></h1>",
  },
  {
    section: "optimistic closing",
    name: "unterminated gfm autolink at end of paragraph auto-closes",
    markdown: "Visit https://github.com",
    html: "<p>Visit <a href=\"https://github.com\">https://github.com</a></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated gfm email autolink at end auto-closes",
    markdown: "Email user@example.com",
    html: "<p>Email <a href=\"mailto:user@example.com\">user@example.com</a></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated www autolink at end auto-closes",
    markdown: "Visit www.github.com",
    html: "<p>Visit <a href=\"http://www.github.com\">www.github.com</a></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated fenced code block consumes rest of document",
    markdown: "```\nunterminated code",
    html: "<pre><code>unterminated code\n</code></pre>",
  },
  {
    section: "optimistic closing",
    name: "unterminated indented code block consumes rest of document",
    markdown: "    unterminated indented code",
    html: "<pre><code>unterminated indented code\n</code></pre>",
  },
  {
    section: "optimistic closing",
    name: "unterminated atx heading with content consumes rest of line as heading",
    markdown: "# Heading *em",
    html: "<h1>Heading <em>em</em></h1>",
  },
  {
    section: "optimistic closing",
    name: "unterminated block quote consumes to end",
    markdown: "> unterminated quote",
    html: "<blockquote><p>unterminated quote</p></blockquote>",
  },
  {
    section: "optimistic closing",
    name: "unterminated block quote with lazy continuation consumes both lines",
    markdown: "> line one\nline two",
    html: "<blockquote><p>line one\nline two</p></blockquote>",
  },
  {
    section: "optimistic closing",
    name: "unterminated html inline tag auto-closes angle bracket",
    markdown: "text <span",
    html: "<p>text &lt;span</p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated emphasis with backslash hard break line consumed",
    markdown: "*line one\\\nline two",
    html: "<p><em>line one<br />\nline two</em></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated emphasis after completed emphasis stays separate",
    markdown: "*closed* *open",
    html: "<p><em>closed</em> <em>open</em></p>",
  },
  // --- Edge cases: escaping ---
  {
    section: "escaping",
    name: "multiple consecutive backslashes",
    markdown: "\\\\alpha",
    html: "<p>\\alpha</p>",
  },
  {
    section: "escaping",
    name: "backslash at end of line is hard break",
    markdown: "alpha\\\nbeta",
    html: "<p>alpha<br />\nbeta</p>",
  },
  {
    section: "escaping",
    name: "numeric entity at max code point",
    markdown: "&#1114111;",
    html: "<p>\u{10FFFF}</p>",
  },
  {
    section: "escaping",
    name: "invalid numeric entity renders as replacement character",
    markdown: "&#1114112;",
    html: "<p>�</p>",
  },
  // --- Edge cases: emphasis ---
  {
    section: "emphasis",
    name: "four asterisks is literal",
    markdown: "****",
    html: "<p>****</p>",
  },
  {
    section: "emphasis",
    name: "asterisk emphasis followed by dash is literal",
    markdown: "*-not emphasis*",
    html: "<p>*-not emphasis*</p>",
  },
  {
    section: "emphasis",
    name: "emphasis right before hard break",
    markdown: "*em*  \nnext",
    html: "<p><em>em</em><br />\nnext</p>",
  },
  {
    section: "emphasis",
    name: "emphasis right before backslash hard break",
    markdown: "*em*\\\nnext",
    html: "<p><em>em</em><br />\nnext</p>",
  },
  {
    section: "emphasis",
    name: "underscore emphasis with punctuation boundary opens",
    markdown: "_(alpha)_",
    html: "<p><em>(alpha)</em></p>",
  },
  {
    section: "emphasis",
    name: "four underscores is literal",
    markdown: "____",
    html: "<p>____</p>",
  },
  // --- Edge cases: code spans ---
  {
    section: "code spans",
    name: "code span containing backtick via double backticks",
    markdown: "`` ` ``",
    html: "<p><code>`</code></p>",
  },
  {
    section: "code spans",
    name: "code span with leading and trailing spaces only",
    markdown: "`  `",
    html: "<p><code></code></p>",
  },
  {
    section: "code spans",
    name: "triple backtick code span with double-backtick content",
    markdown: "``` ``inner`` ```",
    html: "<p><code>``inner``</code></p>",
  },
  // --- Edge cases: links ---
  {
    section: "links",
    name: "reference link with internal whitespace in definition label",
    markdown: "[alpha][  beta  ]\n\n[beta]: https://example.com",
    html: "<p><a href=\"https://example.com\">alpha</a></p>",
  },
  {
    section: "links",
    name: "link with empty text and empty destination",
    markdown: "[]()",
    html: "<p><a href=\"\"></a></p>",
  },
  // --- Edge cases: images ---
  {
    section: "images",
    name: "image with reference and title",
    markdown: "![alt][img]\n\n[img]: https://example.com/pic.png \"title\"",
    html: "<p><img src=\"https://example.com/pic.png\" alt=\"alt\" title=\"title\" /></p>",
  },
  // --- Edge cases: autolinks ---
  {
    section: "autolinks",
    name: "www autolink trailing slash is included",
    markdown: "Visit www.example.com/ now.",
    html: "<p>Visit <a href=\"http://www.example.com/\">www.example.com/</a> now.</p>",
  },
  {
    section: "autolinks",
    name: "url autolink with balanced parentheses",
    markdown: "Visit https://en.wikipedia.org/wiki/C_(programming_language).",
    html: "<p>Visit <a href=\"https://en.wikipedia.org/wiki/C_(programming_language)\">https://en.wikipedia.org/wiki/C_(programming_language)</a>.</p>",
  },
  // --- Edge cases: lists ---
  {
    section: "lists",
    name: "ordered list starting at zero",
    markdown: "0. zero\n1. one",
    html: "<ol start=\"0\"><li>zero</li><li>one</li></ol>",
  },
  {
    section: "lists",
    name: "ordered list with letter marker is not a list",
    markdown: "a. not a list\nb. not a list",
    html: "<p>a. not a list\nb. not a list</p>",
  },
  {
    section: "lists",
    name: "triple nested unordered list",
    markdown: "- one\n  - two\n    - three",
    html: "<ul><li>one<ul><li>two<ul><li>three</li></ul></li></ul></li></ul>",
  },
  {
    section: "lists",
    name: "mixed markers at same indent create separate lists",
    markdown: "- alpha\n* beta",
    html: "<ul><li>alpha</li></ul><ul><li>beta</li></ul>",
  },
  {
    section: "lists",
    name: "list item containing only task checkbox",
    markdown: "- [x]",
    html: "<ul><li><input type=\"checkbox\" disabled=\"\" checked=\"\" /></li></ul>",
  },
  {
    section: "lists",
    name: "tight list with nested loose list",
    markdown: "- outer\n  - inner\n\n    inner continuation",
    html: "<ul><li>outer<ul><li><p>inner</p><p>inner continuation</p></li></ul></li></ul>",
  },
  // --- Edge cases: tables ---
  {
    section: "tables",
    name: "table with header row only",
    markdown: "| A | B |\n| - | - |",
    html: "<table><thead><tr><th>A</th><th>B</th></tr></thead></table>",
  },
  {
    section: "tables",
    name: "table with trailing pipe on some rows only",
    markdown: "| A | B |\n| - | - |\n| 1 | 2",
    html: "<table><thead><tr><th>A</th><th>B</th></tr></thead><tbody><tr><td>1</td><td>2</td></tr></tbody></table>",
  },
  {
    section: "tables",
    name: "table row with fewer cells is padded",
    markdown: "| A | B |\n| - | - |\n| 1 |",
    html: "<table><thead><tr><th>A</th><th>B</th></tr></thead><tbody><tr><td>1</td><td></td></tr></tbody></table>",
  },
  // --- Edge cases: block quotes ---
  {
    section: "block quotes",
    name: "block quote containing fenced code and list",
    markdown: "> ```\n> code\n> ```\n>\n> - item",
    html: "<blockquote><pre><code>code\n</code></pre><ul><li>item</li></ul></blockquote>",
  },
  {
    section: "block quotes",
    name: "block quote with only blank lines after marker",
    markdown: "> \n> ",
    html: "<blockquote></blockquote>",
  },
  {
    section: "block quotes",
    name: "triple nested block quote",
    markdown: "> outer\n> > middle\n> > > inner",
    html: "<blockquote><p>outer</p><blockquote><p>middle</p><blockquote><p>inner</p></blockquote></blockquote></blockquote>",
  },
  // --- Edge cases: code blocks ---
  {
    section: "code blocks",
    name: "tilde fenced code block with info string",
    markdown: "~~~ts\ncode\n~~~",
    html: "<pre><code class=\"language-ts\">code\n</code></pre>",
  },
  {
    section: "code blocks",
    name: "fenced code opened by tilde not closed by backtick",
    markdown: "~~~\ncode\n```",
    html: "<pre><code>code\n```\n</code></pre>",
  },
  {
    section: "code blocks",
    name: "indented code with blank line between code lines",
    markdown: "    line one\n\n    line two",
    html: "<pre><code>line one\n\nline two\n</code></pre>",
  },
  // --- Edge cases: html ---
  {
    section: "html",
    name: "self-closing br with slash and space is escaped",
    markdown: "alpha<br />beta",
    html: "<p>alpha&lt;br /&gt;beta</p>",
  },
  {
    section: "html",
    name: "html span nested inside emphasis is escaped",
    markdown: "*<span class=\"x\">text</span>*",
    html: "<p><em>&lt;span class=&quot;x&quot;&gt;text&lt;/span&gt;</em></p>",
  },
  // --- Edge cases: complex documents ---
  {
    section: "complex documents",
    name: "thematic break without blank line after paragraph",
    markdown: "paragraph\n***",
    html: "<p>paragraph</p><hr />",
  },
  {
    section: "complex documents",
    name: "setext heading with inline formatting",
    markdown: "*em* and **strong**\n======",
    html: "<h1><em>em</em> and <strong>strong</strong></h1>",
  },
  {
    section: "complex documents",
    name: "reference definitions separated by blank lines are still collected",
    markdown: "[a]: https://a.com\n\n[b]: https://b.com\n\n[a][b]",
    html: "<p><a href=\"https://b.com\">a</a></p>",
  },
  {
    section: "complex documents",
    name: "many consecutive code spans in one paragraph",
    markdown: "`a` `b` `c` `d` `e`",
    html: "<p><code>a</code> <code>b</code> <code>c</code> <code>d</code> <code>e</code></p>",
  },
  {
    section: "complex documents",
    name: "html comment with blank lines around it is escaped",
    markdown: "alpha\n\n<!-- comment -->\n\nbeta",
    html: "<p>alpha</p><p>&lt;!-- comment --&gt;</p><p>beta</p>",
  },
  {
    section: "complex documents",
    name: "ordered list with mixed paren and dot delimiters",
    markdown: "1. dot\n2) paren",
    html: "<ol><li>dot</li></ol><ol start=\"2\"><li>paren</li></ol>",
  },
  // --- Edge cases: optimistic closing ---
  {
    section: "optimistic closing",
    name: "unterminated formatting in table header auto-closes",
    markdown: "| *A |\n| --- |\n| 1 |",
    html: "<table><thead><tr><th><em>A</em></th></tr></thead><tbody><tr><td>1</td></tr></tbody></table>",
  },
  {
    section: "optimistic closing",
    name: "unterminated strikethrough containing code span auto-closes",
    markdown: "~~del `code",
    html: "<p><del>del <code>code</code></del></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated emphasis inside unterminated link auto-closes both",
    markdown: "[*em](url",
    html: "<p><a href=\"url\"><em>em</em></a></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated angle bracket autolink consumes rest of paragraph",
    markdown: "<https://example.com rest",
    html: "<p><a href=\"https://example.com rest\">https://example.com rest</a></p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated emphasis after backslash escape stays literal",
    markdown: "*em\\",
    html: "<p><em>em</em>\\</p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated code span with only backticks is literal backticks",
    markdown: "``",
    html: "<p>``</p>",
  },
  {
    section: "optimistic closing",
    name: "unterminated emphasis with entity reference auto-closes",
    markdown: "*em &amp; tail",
    html: "<p><em>em &amp; tail</em></p>",
  },
];

const enabledRenderingCases = new Set([
  "paragraphs: single paragraph",
  "paragraphs: two paragraphs",
  "paragraphs: soft line break",
  "paragraphs: hard break with backslash",
  "paragraphs: hard break with two spaces",
  "paragraphs: leading and trailing blank lines",
  "paragraphs: paragraph with leading spaces up to three",
  "paragraphs: multiple consecutive hard breaks",
  "paragraphs: hard break before blank line",
  "paragraphs: paragraph with only whitespace is collapsed",
  "paragraphs: paragraph with leading tabs",
  "escaping: html special characters are escaped in text",
  "escaping: backslash escapes punctuation",
  "escaping: backslash before non escapable character remains",
  "escaping: entity references",
  "escaping: escaped backslash is single backslash",
  "escaping: escaped exclamation prevents image",
  "escaping: decimal numeric character reference",
  "escaping: hex numeric character reference lowercase",
  "escaping: entity references in sequence",
  "headings: atx heading level one",
  "headings: atx heading level six",
  "headings: closing hashes are stripped",
  "headings: more than six hashes is paragraph",
  "headings: escaped heading marker is paragraph",
  "headings: setext heading level one",
  "headings: setext heading level two",
  "headings: heading contains inline emphasis",
  "headings: atx heading without space is not a heading",
  "headings: atx heading with leading spaces",
  "headings: empty atx heading content",
  "headings: atx heading level three after level one",
  "headings: setext heading preceded by blank line",
  "headings: setext heading with leading spaces in text line",
  "headings: setext heading not formed when text has multiple lines before delimiter",
  "thematic breaks: asterisk thematic break",
  "thematic breaks: dash thematic break with spaces",
  "thematic breaks: underscore thematic break",
  "thematic breaks: thematic break with interleaved spaces",
  "thematic breaks: thematic break with more than three characters",
  "thematic breaks: two characters is not a thematic break",
  "thematic breaks: mixed non-homogeneous characters is not a thematic break",
  "thematic breaks: thematic break at start of document",
  "thematic breaks: thematic break without preceding blank line terminates paragraph",
  "emphasis: asterisk emphasis",
  "emphasis: underscore emphasis",
  "emphasis: strong emphasis with asterisks",
  "emphasis: repairs single leading asterisk with double trailing asterisks as strong",
  "emphasis: strong emphasis with underscores",
  "emphasis: nested emphasis inside strong",
  "emphasis: strong inside emphasis",
  "emphasis: intraword underscore does not emphasize",
  "emphasis: intraword asterisk can emphasize",
  "emphasis: triple asterisk is strong plus emphasis",
  "emphasis: triple underscore is strong plus emphasis",
  "emphasis: emphasis cannot cross paragraph boundary",
  "emphasis: emphasis does not open when separated by spaces from content",
  "emphasis: underscore in middle of word stays literal",
  "emphasis: multiple emphases in one paragraph",
  "emphasis: asterisk opens emphasis even before punctuation",
  "strikethrough: simple strikethrough",
  "strikethrough: strikethrough can contain emphasis",
  "strikethrough: single tilde is literal",
  "strikethrough: strikethrough with leading space does not open",
  "strikethrough: strikethrough with only spaces is literal",
  "strikethrough: multiple strikethroughs in one paragraph",
  "strikethrough: strikethrough containing code span",
  "strikethrough: strikethrough containing strong",
  "code spans: simple code span",
  "code spans: code span escapes html",
  "code spans: double backticks allow single backtick",
  "code spans: code span normalizes internal newlines to spaces",
  "code spans: code span strips one leading and trailing space",
  "code spans: code span with only spaces becomes empty",
  "code spans: empty backtick pair is literal backticks",
  "code spans: unmatched backtick count is literal",
  "code spans: code span inside emphasis",
  "code spans: code span inside link text is literal",
  "code spans: multiple newlines in code span collapse to spaces",
  "links: inline link",
  "links: inline link with title",
  "links: link text contains emphasis",
  "links: reference link full",
  "links: reference link collapsed",
  "links: reference link shortcut",
  "links: missing reference remains literal",
  "links: inline link with angle brackets around destination",
  "links: inline link with empty destination",
  "links: inline link with empty text",
  "links: reference link with title in parentheses",
  "links: link containing code span",
  "links: nested link brackets are literal",
  "links: link destination with percent encoding",
  "links: duplicate reference definition uses first",
  "links: directionless link definition",
  "images: inline image",
  "images: inline image with title",
  "images: image alt text is plain text",
  "images: reference image",
  "images: shortcut reference image",
  "images: image with empty alt text",
  "images: image with empty src is rendered without src",
  "images: image inside link",
  "images: image alt text contains characters that need escaping",
  "autolinks: angle bracket autolink",
  "autolinks: email autolink",
  "autolinks: gfm literal url autolink",
  "autolinks: gfm literal www autolink",
  "autolinks: gfm literal email autolink",
  "autolinks: url autolink with path and query",
  "autolinks: email autolink with plus sign",
  "autolinks: gfm www autolink with path",
  "autolinks: url autolink followed by punctuation is not part of link",
  "autolinks: email autolink followed by period",
  "lists: unordered list with hyphens",
  "lists: unordered list with asterisks",
  "lists: unordered list interrupts paragraph after label",
  "lists: ordered list preserves start number",
  "lists: ordered list with right paren delimiter",
  "lists: nested unordered list",
  "lists: nested ordered list",
  "lists: loose unordered list",
  "lists: list item with paragraph continuation",
  "lists: list item with block quote",
  "lists: unordered list with plus sign",
  "lists: blank line in list item starts loose mode",
  "lists: list item with fenced code block",
  "lists: list with mixed unordered markers creates separate lists",
  "lists: ordered list with right paren and start number",
  "lists: ordered list nested inside unordered",
  "lists: unordered list nested inside ordered",
  "lists: ordered list maintains start number with nesting",
  "lists: empty list item",
  "lists: list item with heading",
  "task lists: unchecked task list item",
  "task lists: checked task list item lowercase x",
  "task lists: checked task list item uppercase x",
  "task lists: nested task list items",
  "task lists: task list in ordered list",
  "task lists: task item without space after bracket is not a task",
  "task lists: invalid task format is not a task",
  "task lists: task list item with paragraph continuation",
  "block quotes: simple block quote",
  "block quotes: lazy continuation",
  "block quotes: nested block quotes",
  "block quotes: block quote with list",
  "block quotes: block quote with code block",
  "block quotes: block quote with heading",
  "block quotes: block quote with thematic break",
  "block quotes: empty block quote",
  "block quotes: block quote with lazy continuation and blank line",
  "block quotes: block quote containing paragraph and nested quote",
  "code blocks: indented code block",
  "code blocks: fenced code block with backticks",
  "code blocks: fenced code block with tildes",
  "code blocks: fenced code block with info string",
  "code blocks: fenced code block escapes html",
  "code blocks: unclosed fenced code block consumes to end",
  "code blocks: indented code block follows paragraph",
  "code blocks: fenced code block within list item",
  "code blocks: fenced code block within block quote",
  "code blocks: fenced code block with longer closing fence",
  "code blocks: empty fenced code block",
  "code blocks: fenced code block with blank line at start",
  "code blocks: indented code block preserves indentation",
  "code blocks: fenced code block with trailing spaces in info string",
  "html: inline html is escaped",
  "html: html block is escaped as paragraph text",
  "html: markdown is parsed normally around escaped html text",
  "html: html comment is escaped",
  "html: self-closing html inline is escaped",
  "html: inline html with attributes is escaped",
  "html: html block text is escaped between paragraphs",
  "html: inline html inside emphasis is escaped",
  "html: raw void element is escaped as paragraph text",
  "optimistic closing: unterminated fenced code block consumes rest of document",
  "optimistic closing: unterminated indented code block consumes rest of document",
  "definitions: link definition is not rendered",
  "definitions: link definition can be indented up to three spaces",
  "definitions: four-space indented link definition is code",
  "definitions: link definition with title in parentheses",
  "definitions: link definition label is case-insensitive",
  "definitions: link definition label folding trims whitespace",
  "tables: simple table",
  "tables: table alignments",
  "tables: table without leading and trailing pipes",
  "tables: table cell inline markdown",
  "tables: escaped pipe in table cell",
  "tables: extra table cells are ignored",
  "tables: missing table cells are empty",
  "tables: single column table",
  "tables: table with empty cells",
  "tables: table without body rows",
  "tables: table with multiple body rows",
  "tables: delimiter row with fewer columns than header",
  "tables: table immediately followed by paragraph",
  "tables: table with center alignment only",
  "complex documents: mixed document with heading quote list and table",
  "complex documents: inline precedence code beats emphasis and links",
  "complex documents: link destination containing escaped parenthesis",
  "complex documents: image inside link",
  "complex documents: paragraph with inline image link emphasis and code",
  "complex documents: reference links with images and multiple definitions",
  "complex documents: unicode text and emoji",
  "complex documents: carriage returns normalize to line feeds",
  "complex documents: null character replacement",
  "complex documents: empty string",
  "complex documents: only whitespace and blank lines",
  "complex documents: only blank lines",
  "complex documents: multiple consecutive thematic breaks",
  "complex documents: heading after heading without blank line",
  "complex documents: deeply nested block quote list and code",
  "complex documents: list with task block quote and nested list",
  "complex documents: code block preserves blank lines internally",
  "complex documents: table with inline emphasis code and link in cells",
  "complex documents: setext heading followed by paragraph",
  "complex documents: strikethrough spanning most of paragraph",
  "complex documents: triple backtick fence with backtick content",
  "complex documents: thousands of characters in single paragraph",
  "complex documents: code span with literal tilde characters",
  "complex documents: link text contains backslash escapes",
  "complex documents: bullet list with flat items at varying indentation",
  "complex documents: ordered list with reversed numbers",
  "complex documents: tight list with block quote at end",
  "complex documents: hard break in list item",
  "optimistic closing: unterminated asterisk emphasis auto-closes at end",
  "optimistic closing: unterminated underscore emphasis auto-closes at end",
  "optimistic closing: unterminated double asterisk strong auto-closes at end",
  "optimistic closing: unterminated double underscore strong auto-closes at end",
  "optimistic closing: unterminated triple asterisk strong-em auto-closes at end",
  "optimistic closing: unterminated triple underscore strong-em auto-closes at end",
  "optimistic closing: unterminated strikethrough auto-closes at end",
  "optimistic closing: unterminated code span auto-closes at end",
  "optimistic closing: unterminated inline link auto-closes paren at end",
  "optimistic closing: unterminated inline link auto-closes bracket and paren",
  "optimistic closing: unterminated link bracket before open paren auto-closes",
  "optimistic closing: unterminated inline image auto-closes paren at end",
  "optimistic closing: unterminated angle bracket autolink auto-closes at end",
  "optimistic closing: unterminated angle bracket email auto-closes at end",
  "optimistic closing: emphasis inside unterminated strong auto-closes both",
  "optimistic closing: strong inside unterminated emphasis auto-closes both",
  "optimistic closing: unterminated strikethrough containing emphasis auto-closes",
  "optimistic closing: unterminated emphasis containing strikethrough auto-closes",
  "optimistic closing: unterminated link with emphasis in text auto-closes",
  "optimistic closing: unterminated emphasis surrounding link auto-closes",
  "optimistic closing: triple nested unterminated auto-closes all layers",
  "optimistic closing: unterminated formatting before text then normal text follows",
  "optimistic closing: unterminated formatting mid-paragraph consumes to end",
  "optimistic closing: unterminated formatting before properly closed formatting",
  "optimistic closing: properly closed formatting before unterminated formatting",
  "optimistic closing: adjacent unterminated spans auto-close independently",
  "optimistic closing: unterminated formatting at start of paragraph with line break",
  "optimistic closing: unterminated formatting in heading auto-closes",
  "optimistic closing: unterminated formatting in block quote auto-closes",
  "optimistic closing: unterminated formatting in list item auto-closes",
  "optimistic closing: unterminated formatting in tight list continuation auto-closes",
  "optimistic closing: unterminated formatting in table cell auto-closes",
  "optimistic closing: unterminated double backtick code span auto-closes",
  "optimistic closing: unterminated link with title auto-closes paren and title quote",
  "optimistic closing: unterminated link with single-quote title auto-closes",
  "optimistic closing: unterminated link with parenthesized title auto-closes",
  "optimistic closing: unterminated image with title auto-closes",
  "optimistic closing: only opening emphasis marker without content produces no output",
  "optimistic closing: multiple unterminated same-type spans in paragraph",
  "optimistic closing: unterminated strong in link text auto-closes",
  "optimistic closing: unterminated code span in link text auto-closes",
  "optimistic closing: unterminated formatting in setext heading auto-closes",
  "optimistic closing: unterminated atx heading with content consumes rest of line as heading",
  "optimistic closing: unterminated emphasis with backslash hard break line consumed",
  "optimistic closing: unterminated emphasis after completed emphasis stays separate",
  "optimistic closing: unterminated block quote consumes to end",
  "optimistic closing: unterminated html inline tag auto-closes angle bracket",
  "optimistic closing: unterminated gfm autolink at end of paragraph auto-closes",
  "optimistic closing: unterminated gfm email autolink at end auto-closes",
  "optimistic closing: unterminated www autolink at end auto-closes",
  "optimistic closing: unterminated block quote with lazy continuation consumes both lines",
  // Edge cases: escaping
  "escaping: multiple consecutive backslashes",
  "escaping: backslash at end of line is hard break",
  "escaping: numeric entity at max code point",
  "escaping: invalid numeric entity renders as replacement character",
  // Edge cases: emphasis
  "emphasis: four asterisks is literal",
  "emphasis: asterisk emphasis followed by dash is literal",
  "emphasis: emphasis right before hard break",
  "emphasis: emphasis right before backslash hard break",
  "emphasis: underscore emphasis with punctuation boundary opens",
  "emphasis: four underscores is literal",
  // Edge cases: code spans
  "code spans: code span containing backtick via double backticks",
  "code spans: code span with leading and trailing spaces only",
  "code spans: triple backtick code span with double-backtick content",
  // Edge cases: links
  "links: reference link with internal whitespace in definition label",
  "links: link with empty text and empty destination",
  // Edge cases: images
  "images: image with reference and title",
  // Edge cases: autolinks
  "autolinks: www autolink trailing slash is included",
  "autolinks: url autolink with balanced parentheses",
  // Edge cases: lists
  "lists: ordered list starting at zero",
  "lists: ordered list with letter marker is not a list",
  "lists: triple nested unordered list",
  "lists: mixed markers at same indent create separate lists",
  "lists: list item containing only task checkbox",
  "lists: tight list with nested loose list",
  // Edge cases: tables
  "tables: table with header row only",
  "tables: table with trailing pipe on some rows only",
  "tables: table row with fewer cells is padded",
  // Edge cases: block quotes
  "block quotes: block quote containing fenced code and list",
  "block quotes: block quote with only blank lines after marker",
  "block quotes: triple nested block quote",
  // Edge cases: code blocks
  "code blocks: tilde fenced code block with info string",
  "code blocks: fenced code opened by tilde not closed by backtick",
  "code blocks: indented code with blank line between code lines",
  // Edge cases: html
  "html: self-closing br with slash and space is escaped",
  "html: html span nested inside emphasis is escaped",
  // Edge cases: complex documents
  "complex documents: thematic break without blank line after paragraph",
  "complex documents: setext heading with inline formatting",
  "complex documents: reference definitions separated by blank lines are still collected",
  "complex documents: many consecutive code spans in one paragraph",
  "complex documents: html comment with blank lines around it is escaped",
  "complex documents: ordered list with mixed paren and dot delimiters",
  // Edge cases: optimistic closing
  "optimistic closing: unterminated formatting in table header auto-closes",
  "optimistic closing: unterminated strikethrough containing code span auto-closes",
  "optimistic closing: unterminated emphasis inside unterminated link auto-closes both",
  "optimistic closing: unterminated angle bracket autolink consumes rest of paragraph",
  "optimistic closing: unterminated emphasis after backslash escape stays literal",
  "optimistic closing: unterminated code span with only backticks is literal backticks",
  "optimistic closing: unterminated emphasis with entity reference auto-closes",
]);

describe("GetDown GFM rendering", () => {
  for (const renderingCase of gfmRenderingCases) {
    const testName = `${renderingCase.section}: ${renderingCase.name}`;
    const runner = enabledRenderingCases.has(testName) ? test : test.todo;
    runner(testName, () => {
      expect(render(renderingCase.markdown)).toBe(renderingCase.html);
    });
  }
});

describe("GetDown renderer overrides", () => {
  test("allows link and bold components to be replaced", () => {
    function AppLink({ href, title, children }: GetDownLinkProps) {
      return <a className="app-link" href={href} title={title} target="_blank" rel="noopener noreferrer">{children}</a>;
    }

    function AppBold({ children }: GetDownBoldProps) {
      return <b className="app-bold">{children}</b>;
    }

    expect(renderWithProps({ content: "**Read** [docs](https://example.com)", onLinkComponent: AppLink, onBoldComponent: AppBold })).toBe(
      "<p><b class=\"app-bold\">Read</b> <a class=\"app-link\" href=\"https://example.com\" target=\"_blank\" rel=\"noopener noreferrer\">docs</a></p>",
    );
  });

  test("allows inline code to be replaced", () => {
    function InlineCode({ value }: GetDownInlineCodeProps) {
      return <code className="app-inline-code" data-code={value}>{value}</code>;
    }

    expect(renderWithProps({ content: "Use `getdown`.", onInlineCodeComponent: InlineCode })).toBe(
      "<p>Use <code class=\"app-inline-code\" data-code=\"getdown\">getdown</code>.</p>",
    );
  });

  test("allows code blocks and table pieces to be replaced", () => {
    function CodeBlock({ code, language }: GetDownCodeBlockProps) {
      return <pre className="app-code" data-language={language}><code>{code}</code></pre>;
    }

    function Table({ children }: GetDownTableProps) {
      return <table className="app-table">{children}</table>;
    }

    function TableCell({ align, children }: GetDownTableCellProps) {
      return <td className="app-cell" data-align={align}>{children}</td>;
    }

    expect(renderWithProps({
      content: "```ts\nconst x = 1;\n```\n\n| A | B |\n| - | -: |\n| 1 | 2 |",
      onCodeBlockComponent: CodeBlock,
      onTableComponent: Table,
      onTableCellComponent: TableCell,
    })).toBe(
      "<pre class=\"app-code\" data-language=\"ts\"><code>const x = 1;\n</code></pre><table class=\"app-table\"><thead><tr><th>A</th><th align=\"right\">B</th></tr></thead><tbody><tr><td class=\"app-cell\">1</td><td class=\"app-cell\" data-align=\"right\">2</td></tr></tbody></table>",
    );
  });

  test("filters unsafe link and image urls by default", () => {
    expect(render("[x](javascript:alert) ![alt](data:text/html,x)")).toBe("<p><a>x</a> <img alt=\"alt\" /></p>");
  });

  test("allows app-specific url sanitizers", () => {
    expect(renderWithProps({
      content: "[x](app://thread/1) ![alt](cid:image-1)",
      onSanitizeLinkHref: (href) => href.startsWith("app://") ? href : undefined,
      onSanitizeImageSrc: (src) => src.startsWith("cid:") ? src : undefined,
    })).toBe("<p><a href=\"app://thread/1\">x</a> <img src=\"cid:image-1\" alt=\"alt\" /></p>");
  });
});
