#!/usr/bin/env bun
/** Build the Metidos xmloxide WebAssembly parser wrapper. */

import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { spawnSync } from "node:child_process";

const root = import.meta.dir;
const target = "wasm32-unknown-unknown";
const cargo = spawnSync("cargo", ["build", "--release", "--target", target], {
  cwd: root,
  stdio: "inherit",
});
if (cargo.status !== 0) {
  process.exit(cargo.status ?? 1);
}

const source = join(
  root,
  "target",
  target,
  "release",
  "metidos_xmloxide_wasm.wasm",
);
const dest = join(root, "dist", "metidos_xmloxide_wasm.wasm");
mkdirSync(dirname(dest), { recursive: true });
copyFileSync(source, dest);
console.log(`Wrote ${dest}`);

const wasmBase64 = readFileSync(dest).toString("base64");
const bundleDest = join(root, "dist", "metidos_xmloxide_wasm.cjs");
writeFileSync(
  bundleDest,
  [
    "'use strict';",
    "// Generated by native/xmloxide-wasm/build.ts.",
    "const wasmBase64 = " + JSON.stringify(wasmBase64) + ";",
    "function wasmBytes() { return Buffer.from(wasmBase64, 'base64'); }",
    "function instantiate(imports = {}) { return WebAssembly.instantiate(wasmBytes(), imports); }",
    "module.exports = { instantiate, wasmBase64, wasmBytes };",
    "",
  ].join("\n"),
);
console.log(`Wrote ${bundleDest}`);
